spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.106/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.1.106
    port: 6379
server:
  context-path: /sell

wechat:
  mpAppId: wxd898fcb01713c658
  mpAppSecret: 6f9ddaa9913745ecaf34d141a970571f
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  KeyPath: D:/ex/WorkSpace/sell/h5.p12
  notifyUrl: http://sgwe.natapp1.cc/sell/pay/notify
  templateId:
    orderStatus: Do7mO-pkwOn88T-OI969fDrldREL2ZRP-L9_sWPNnDA

projectUrl:
  wechatAuthorize: http://sgwe.natapp1.cc
  wechatOpenAuthorize: http://sgwe.natapp1.cc
  sell: http://sgwe.natapp1.cc

